### ISSUE TITLE
Disseny de la base de dades

### ISSUE THREAD

**Issue by 0x1026** [Projecte-UrbanTree/UrbanTree#1]
Dissenyar l'estructura de la base de dades per al projecte, que estarà emmagatzemada en **MariaDB**.
Aquesta tasca implica definir les taules, les relacions entre elles, els camps i les seves propietats, així com altres aspectes relacionats amb la integritat i eficiència del  sistema.

> MariaDB és una base de dades relacional d'alt rendiment, compatible amb MySQL, però amb diverses millores.

> [!WARNING]
> Disposem de [Database Naming Convention](), el qual s'ha de seguir per dissenyar correctament la base de dades.

Enllaç del diagrama: https://dbdiagram.io/d/M12-UrbanTree-6711167697a66db9a3577b41

**Comment by 0x1026** [comment]
La base de dades ha estat incorporada la branca main, donem per vàlid el disseny de la base de dades.
Qualsevol canvi relacionat amb la base de dades s'haurà de proposar amb una nova issue amb l'etiqueta `area/database`.

**Comment by SandraFerrando** [comment]
![UrbanTree diagrama simplificat](https://github.com/user-attachments/assets/57dc4446-1113-44fd-a21d-af1a01ff1956)
