### ISSUE TITLE
.vscode

### ISSUE THREAD

**Issue by XaviFiblaEdu** [Projecte-UrbanTree/UrbanTree#26]
Normalment, la carpeta .vscode no s'hauria de pujar al GitHub, ja que conté configuracions d'editor específiques de l'usuari que no són necessàries per al projecte en si. La configuració dins d’aquesta carpeta, com ara extensions i configuracions locals de Visual Studio Code, pot variar entre desenvolupadors, i pujar-la pot causar conflictes o crear confusió.

**Comment by 0x1026** [comment]
Bones Xavi,

La carpeta `.vscode` es pot incloure en un repositori si la configuració que conté és important per al projecte. Això assegura un entorn coherent entre tots els desenvolupadors.

### Prioritat de Configuracions de VS Code
1. Configuració predeterminada de VS Code.
2. Configuració de l'usuari (global).
3. Configuració de l'àrea de treball (workspace).
4. Configuració per carpeta (multi-workspace).

### Recomanacions per incloure `.vscode` en un repositori
- **Incloure només el necessari:** Com configuracions de format, depuració o extensions recomanades.
- **Evitar configuracions personals:** Ajustos com temes o preferències d’usuari haurien de romandre a `settings.json` global.

Així, incloure `.vscode` és útil si mantens només la configuració necessària i rellevant per al projecte.

**Comment by XaviFiblaEdu** [comment]
No ho teniu així, acordeu-ho i reviseu-ho per favor

**Comment by 0x1026** [comment]
@Projecte-UrbanTree/alumnat, alguna opinió a comentar per aquí o preferiu que ho parlem el dilluns 04/11/2024?

**Comment by 0x1026** [comment]
Es reprograma parlar d'aquesta issue el proper dilluns 11/11.

**Comment by 0x1026** [comment]
Recentment ens hem reunit i entenem el que dius però s'ha acordat que per facilitar el desenvolupament entre tots, i no configurar cop enrere cop certa configuració, utilitzarem aquesta carpeta que serà revisada pels equips mencionants en l'anterior comentari.
