### ISSUE TITLE
Definir i justificar l'aspecte i la UI

### ISSUE THREAD

**Issue by 0x1026** [Projecte-UrbanTree/UrbanTree#3]
Cada membre de l'equip ha de definir individualment l'aspecte i la interfície d'usuari (UI) de l'aplicació. Això inclou elements com la disposició de les pantalles, l'ús de colors, tipografia, icones i altres components visuals que ajudin a crear una experiència d'usuari coherent i atractiva.

Aquesta tasca està composta per dues fases, atès que s'ha de fer individualment per desprès fer una tria i decisió en grup.

**Fases de la tasca**:
1. **Definició individual**: Cada persona ha de crear una proposta pròpia de l'aspecte i interfície de l'aplicació. És important que, a més de presentar el disseny, s'expliquin i justifiquin les eleccions fetes. Per exemple, per què s'ha triat un cert esquema de colors, quins avantatges té l'estructura proposada o com pot millorar la usabilitat de l'aplicatiu.
   
2. **Discussió en grup**: Un cop totes les propostes individuals estiguin completes, es farà una revisió conjunta on l'equip discutirà els diferents dissenys. L'objectiu és seleccionar una proposta final o combinar elements de diverses idees per crear una versió que agradi a tothom i compleixi els requisits funcionals i estètics de l'aplicació.

La **proposta individual** ha de constar del següent:

- Logotip
- Paleta de colors
- Font de lletra
- Icones

I documentada en el següent fitxer del Drive:

https://docs.google.com/document/d/1EcYhef_XRwjv5gXxRsP1R4IxCq0YRiWqv6kcmXbM_js/edit

**Comment by albert1413** [comment]
https://www.design.com/maker/logos/page2?Text=UrbanTree&SearchText=nature&WasModalContinueClicked=true&isMobile=false

**Comment by 24Victor** [comment]
https://www.canva.com/design/DAGUOfvDK1s/ZoHNeFM4JTYF678MbD618A/edit?utm_content=DAGUOfvDK1s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by 0x1026** [comment]
Com heu afegit els vostres dissenys al document del Drive, oculto els vostres comentaris 🙆🏻‍♂️

**Comment by 0x1026** [comment]
Perdoneu per les mencions, si la repo està privada, només em deixava assignar una persona.

**Comment by 0x1026** [comment]
Estava pensant que, la pantalla administrativa de crear tasca, podria haver dos botons per triar de què tasca parlem[^1] (si d'una preventiva o d'una correctiva) i segons el seleccionat, mostrar els diferents inputs:

1. Manteniment:
1.1. Possible recurrencia
2. Incidència:
2.1. Fotografia

Entre altres...

Què us pareix la idea?

[^1]: <img width="259" alt="image" src="https://github.com/user-attachments/assets/abd0fb08-13c4-40f7-a920-a0d9954aed5a">

**Comment by CODEmartigarcia** [comment]
Bonissim, s’hauria d’assegurar que manteniment no tingués fotografía o si
fos opcional i incidència que fos obligatoria, què penses/eu? Estic a
favor!🙋‍♂️

**Comment by 0x1026** [comment]
Tanquem issue atès que ens hem reunit, i ja s'ha acordat la proposta col·lectiva!

Des d'[aquí](https://docs.google.com/document/d/1EcYhef_XRwjv5gXxRsP1R4IxCq0YRiWqv6kcmXbM_js/edit) podeu veure les diferentes propostes dels companys o la [proposta col·lectiva](https://docs.google.com/document/d/1EcYhef_XRwjv5gXxRsP1R4IxCq0YRiWqv6kcmXbM_js/edit?tab=t.0#heading=h.5o34qbi2guwn).
